version: '3.4'

services:
  dddeftelingpark:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FairyTaleUrl=http://dddeftelingfairytales:3999
      - ParkUrl=http://dddeftelingpark:3998
      - RideUrl=http://dddeftelingrides:3997
      - StandUrl=http://dddeftelingstands:3996
      - VisitorUrl=http://dddeftelingvisitors:3995
    ports:
      - "3998:3998"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  dddeftelingrides:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FairyTaleUrl=http://dddeftelingfairytales:3999
      - ParkUrl=http://dddeftelingpark:3998
      - RideUrl=http://dddeftelingrides:3997
      - StandUrl=http://dddeftelingstands:3996
      - VisitorUrl=http://dddeftelingvisitors:3995
    ports:
      - "3997:3997"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  dddeftelingfairytales:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FairyTaleUrl=http://dddeftelingfairytales:3999
      - ParkUrl=http://dddeftelingpark:3998
      - RideUrl=http://dddeftelingrides:3997
      - StandUrl=http://dddeftelingstands:3996
      - VisitorUrl=http://dddeftelingvisitors:3995
    ports:
      - "3999:3999"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  dddeftelingvisitors:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FairyTaleUrl=http://dddeftelingfairytales:3999
      - ParkUrl=http://dddeftelingpark:3998
      - RideUrl=http://dddeftelingrides:3997
      - StandUrl=http://dddeftelingstands:3996
      - VisitorUrl=http://dddeftelingvisitors:3995
    ports:
      - "3995:3995"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  dddeftelingstands:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FairyTaleUrl=http://dddeftelingfairytales:3999
      - ParkUrl=http://dddeftelingpark:3998
      - RideUrl=http://dddeftelingrides:3997
      - StandUrl=http://dddeftelingstands:3996
      - VisitorUrl=http://dddeftelingvisitors:3995
    ports:
      - "3996:3996"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
